# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e5d29b2d6b6e1225e3c30a29c3697b93d27cd4244ee0ba33bec22cb5c9a3556b2d49095237e2d5dacc3075304baeee09ed4feac319fa4a29a45ec24131026d1

test:
  secret_key_base: b7526ca25d1f71e64eeedabc0c1dd76e224033a19da01051155d93929eb4c759415e0a260b838475b81159b9ff77b9c5f9e14ecb958b831d54d2371b4197a1bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
